name: Court Booking Automation

on:
  # Run manually
  workflow_dispatch:
    inputs:
      days_ahead:
        description: 'Days ahead to book (default: 14)'
        required: false
        default: '14'
        type: string

  # Run on schedule at 5:00 PM Mountain Time (Mon/Thu)
  schedule:
    # During MDT (March-November): Monday/Thursday at 11 PM UTC = 5 PM MDT
    - cron: '0 23 * 3-10 1,4'  # March through October
    - cron: '0 23 1-7 11 1,4'  # November 1-7 (before DST ends, ~first Sunday)
    # During MST (November-March): Tuesday/Friday at 12 AM UTC = 5 PM MST (previous day)
    - cron: '0 0 8-30 11 2,5'  # November 8-30 (after DST ends)
    - cron: '0 0 * 12 2,5'     # December
    - cron: '0 0 * 1-2 2,5'    # January through February
    - cron: '0 0 1-9 3 2,5'    # March 1-9 (before DST starts, ~second Sunday)

env:
  # Set environment variables from secrets
  ESC_USERNAME: ${{ secrets.ESC_USERNAME }}
  ESC_PASSWORD: ${{ secrets.ESC_PASSWORD }}

jobs:
  book-court:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg unzip xvfb

    - name: Get Chrome version for caching
      id: chrome-version
      run: |
        # Get the latest stable Chrome version for cache key
        CHROME_VERSION=$(curl -s https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions | jq -r '.versions[0].version')
        echo "version=$CHROME_VERSION" >> $GITHUB_OUTPUT

    - name: Cache Google Chrome
      id: chrome-cache
      uses: actions/cache@v4
      with:
        path: |
          /opt/google/chrome
          /usr/bin/google-chrome
          /usr/bin/google-chrome-stable
        key: chrome-${{ steps.chrome-version.outputs.version }}-${{ runner.os }}

    - name: Install Google Chrome
      if: steps.chrome-cache.outputs.cache-hit != 'true'
      run: |
        # Disable man-db triggers to prevent hanging
        sudo mv /usr/bin/mandb /usr/bin/mandb.bak 2>/dev/null || true

        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update

        # Install Chrome with optimized settings for CI
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get install -y --no-install-recommends google-chrome-stable

        # Restore mandb if it was moved
        sudo mv /usr/bin/mandb.bak /usr/bin/mandb 2>/dev/null || true

    - name: Cache ChromeDriver
      id: chromedriver-cache
      uses: actions/cache@v4
      with:
        path: /usr/bin/chromedriver
        key: chromedriver-${{ steps.chrome-version.outputs.version }}-${{ runner.os }}

    - name: Install ChromeDriver
      if: steps.chromedriver-cache.outputs.cache-hit != 'true'
      run: |
        # Ensure Chrome is available first
        if ! command -v google-chrome &> /dev/null; then
          echo "Chrome not found, installing it first..."
          # Disable man-db triggers to prevent hanging
          sudo mv /usr/bin/mandb /usr/bin/mandb.bak 2>/dev/null || true

          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update

          # Install Chrome with optimized settings for CI
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y --no-install-recommends google-chrome-stable

          # Restore mandb if it was moved
          sudo mv /usr/bin/mandb.bak /usr/bin/mandb 2>/dev/null || true
        fi

        # Install ChromeDriver using Chrome for Testing API
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3)
        echo "Chrome version: $CHROME_VERSION"

        # Use Chrome for Testing API to get matching ChromeDriver
        CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | \
          jq -r --arg version "$CHROME_VERSION" '.versions[] | select(.version == $version) | .downloads.chromedriver[]? | select(.platform == "linux64") | .url' | head -1)

        if [ -z "$CHROMEDRIVER_URL" ]; then
          echo "No exact match found for Chrome $CHROME_VERSION, getting latest stable ChromeDriver..."
          # Get latest stable ChromeDriver
          CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json" | \
            jq -r '.channels.Stable.downloads.chromedriver[]? | select(.platform == "linux64") | .url')
        fi

        echo "ChromeDriver URL: $CHROMEDRIVER_URL"

        if [ -n "$CHROMEDRIVER_URL" ]; then
          wget -q "$CHROMEDRIVER_URL" -O chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          rm -rf chromedriver-linux64 chromedriver-linux64.zip
        else
          echo "Failed to get ChromeDriver URL, using webdriver-manager as fallback"
          pip install webdriver-manager
          python -c "
            from webdriver_manager.chrome import ChromeDriverManager
            import shutil
            driver_path = ChromeDriverManager().install()
            shutil.copy(driver_path, '/usr/bin/chromedriver')
          " && sudo chmod +x /usr/bin/chromedriver
        fi

        # Verify installation
        /usr/bin/chromedriver --version

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}-selenium-dotenv-webdriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium python-dotenv webdriver-manager

    - name: Create .env file from secrets
      run: |
        echo "ESC_USERNAME=${{ secrets.ESC_USERNAME }}" > .env
        echo "ESC_PASSWORD=${{ secrets.ESC_PASSWORD }}" >> .env
        echo "ESC_ADDITIONAL_PLAYER=${{ secrets.ESC_ADDITIONAL_PLAYER }}" >> .env

    - name: Run court booking automation
      run: |
        # Use xvfb for headless display
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

        # Run the smart court booking script
        # Arguments: <days_ahead> <time> [duration]
        # Monday/Thursday at 5:00 PM, booking 14 days (2 weeks) in the future
        python smart_court_booking.py ${{ inputs.days_ahead || '14' }} "5:00 PM" 45
      env:
        # Force headless mode for GitHub Actions
        GITHUB_ACTIONS: true

    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failure-screenshots
        path: |
          *.png
          screenshot*.png
        retention-days: 7
